include $(APPDIR)/Make.defs

PROGNAME  = jianmu
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 16384
MODULE    = $(CONFIG_EXAMPLES_JIANMU)

MAINSRC = jianmu_main.c v10_api.c v10_infer.c semantic_index.c

include $(APPDIR)/Application.mk
